import type { Course } from "@/lib/content/types";

export const courses: Course[] = [
  {
    id: "how-computing-works",
    slug: "how-computing-works",
    trackSlug: "foundations",
    title: "How Computing & the Web Work",
    description: "The mental model behind code, files, and the internet.",
    order: 0,
    difficulty: "beginner",
    estimatedHours: 2,
  },
  {
    id: "html-css-fundamentals",
    slug: "html-css-fundamentals",
    trackSlug: "web-html-css",
    title: "HTML & CSS Fundamentals",
    description: "Build structured, styled, responsive, accessible pages from scratch.",
    order: 0,
    difficulty: "beginner",
    estimatedHours: 6,
  },
  {
    id: "javascript-fundamentals",
    trackSlug: "javascript",
    slug: "javascript-fundamentals",
    title: "JavaScript Fundamentals",
    description: "Programming logic, the DOM, events, and asynchronous data in the browser.",
    order: 0,
    difficulty: "beginner",
    estimatedHours: 7,
  },
  {
    id: "python-fundamentals",
    trackSlug: "python",
    slug: "python-fundamentals",
    title: "Python Fundamentals",
    description: "General-purpose programming with Python, from syntax to testing.",
    order: 0,
    difficulty: "beginner",
    estimatedHours: 7,
  },
  {
    id: "git-apis-sql",
    trackSlug: "git-api-sql",
    slug: "git-apis-sql",
    title: "Git, APIs & SQL",
    description: "Collaborate with version control, consume APIs, and query relational data.",
    order: 0,
    difficulty: "intermediate",
    estimatedHours: 7,
  },
  {
    id: "ai-foundations",
    trackSlug: "ai-llm-rag",
    slug: "ai-foundations",
    title: "AI, LLMs & RAG",
    description:
      "From neural network intuition to production retrieval-augmented generation and agents.",
    order: 0,
    difficulty: "intermediate",
    estimatedHours: 8,
  },
];
