import type { CategoryInput } from "@/lib/directory/types";

/**
 * The canonical 16-category taxonomy. Only categories with substantive,
 * validated technology guides (and, where real, courses) are public in this
 * phase -- Quantitative Aptitude, Reasoning, and Career/GD Prep are
 * registered (so the type system and future content can reference them) but
 * kept `publicVisibility: false` until Phase 5 actually builds their
 * content. `scripts/validate-content.ts` fails the build if a public
 * category has zero technologies, so this can't silently drift.
 */
export const categories: CategoryInput[] = [
  {
    id: "foundations",
    slug: "foundations",
    name: "Foundations",
    shortDescription: "The mental model every developer needs before writing a line of code.",
    introduction:
      "Foundations covers how computers, files, and the web actually work, plus the habits (reading docs, using an editor and terminal, asking a well-formed question) that make every later topic easier. Start here if you've never written code before.",
    icon: "foundations",
    order: 0,
    searchKeywords: ["basics", "getting started", "beginner", "intro"],
    relatedCategoryIds: ["developer-tools", "frontend"],
    audience: "Complete beginners with zero prior coding experience.",
    publicVisibility: true,
    featured: true,
  },
  {
    id: "frontend",
    slug: "frontend",
    name: "Frontend Development",
    shortDescription: "Structure, style, and program what learners see and interact with.",
    introduction:
      "Frontend development is everything that runs in the browser: markup, styling, layout, and client-side interactivity, from plain HTML/CSS/JavaScript through the frameworks built on top of them.",
    icon: "frontend",
    order: 1,
    searchKeywords: ["ui", "web development", "browser", "client-side"],
    relatedCategoryIds: ["backend", "programming-languages"],
    audience: "Beginners through intermediate developers building for the browser.",
    publicVisibility: true,
    featured: true,
  },
  {
    id: "backend",
    slug: "backend",
    name: "Backend Development",
    shortDescription: "Servers, APIs, and the logic behind what the frontend calls.",
    introduction:
      "Backend development covers how servers receive requests, run application logic, talk to databases, and return responses -- the half of the web that doesn't run in a browser.",
    icon: "backend",
    order: 2,
    searchKeywords: ["server-side", "api", "backend framework"],
    relatedCategoryIds: ["databases", "programming-languages", "cloud-devops"],
    audience: "Developers who know some programming and want to build server-side systems.",
    publicVisibility: true,
    featured: true,
  },
  {
    id: "programming-languages",
    slug: "programming-languages",
    name: "Programming Languages",
    shortDescription: "General-purpose languages, independent of any one framework.",
    introduction:
      "Every framework is built on a language. This category covers the languages themselves -- syntax, type systems, and idioms -- separately from the frameworks and platforms built on top of them.",
    icon: "programming-languages",
    order: 3,
    searchKeywords: ["language", "syntax", "compiler", "interpreter"],
    relatedCategoryIds: ["frontend", "backend", "mobile"],
    audience: "Anyone learning a language's fundamentals, independent of a specific framework.",
    publicVisibility: true,
    featured: true,
  },
  {
    id: "mobile",
    slug: "mobile",
    name: "Mobile Development",
    shortDescription: "Building apps for phones and tablets, native and cross-platform.",
    introduction:
      "Mobile development covers the languages and cross-platform frameworks used to build iOS and Android apps, from a single native language to frameworks that target both platforms from one codebase.",
    icon: "mobile",
    order: 4,
    searchKeywords: ["ios", "android", "app development", "cross-platform"],
    relatedCategoryIds: ["programming-languages", "frontend"],
    audience: "Developers with some programming background who want to build mobile apps.",
    publicVisibility: true,
    featured: false,
  },
  {
    id: "databases",
    slug: "databases",
    name: "Databases",
    shortDescription: "Storing, querying, and modeling data reliably.",
    introduction:
      "Databases covers relational (SQL) and non-relational data storage: how to model data, query it efficiently, and choose the right kind of database for a given problem.",
    icon: "databases",
    order: 5,
    searchKeywords: ["sql", "nosql", "data storage", "query"],
    relatedCategoryIds: ["backend", "data-science"],
    audience: "Developers who need to store and query application or analytical data.",
    publicVisibility: true,
    featured: true,
  },
  {
    id: "data-science",
    slug: "data-science",
    name: "Data Science and Analytics",
    shortDescription: "Working with data: analysis, tooling, and the numeric Python stack.",
    introduction:
      "Data science and analytics covers the tools used to explore, clean, analyze, and draw conclusions from data -- from spreadsheets through the Python scientific-computing stack.",
    icon: "data-science",
    order: 6,
    searchKeywords: ["data analysis", "statistics", "numpy", "pandas"],
    relatedCategoryIds: ["programming-languages", "artificial-intelligence", "databases"],
    audience: "Developers and analysts who want to work with real datasets.",
    publicVisibility: true,
    featured: false,
  },
  {
    id: "artificial-intelligence",
    slug: "artificial-intelligence",
    name: "Artificial Intelligence",
    shortDescription: "Machine learning, LLMs, retrieval-augmented generation, and AI agents.",
    introduction:
      "Artificial intelligence covers the concepts behind modern AI systems: how models learn, how large language models work, and how to build grounded, cited applications on top of them responsibly.",
    icon: "artificial-intelligence",
    order: 7,
    searchKeywords: ["ai", "ml", "llm", "machine learning", "genai", "rag"],
    relatedCategoryIds: ["data-science", "programming-languages"],
    audience: "Developers who want to understand and build with modern AI systems.",
    publicVisibility: true,
    featured: true,
  },
  {
    id: "cloud-devops",
    slug: "cloud-devops",
    name: "Cloud and DevOps",
    shortDescription: "Deploying, scaling, and automating software delivery.",
    introduction:
      "Cloud and DevOps covers the major cloud platforms, containerization, and the automation (CI/CD, infrastructure as code) that gets code from a laptop to production reliably.",
    icon: "cloud-devops",
    order: 8,
    searchKeywords: ["cloud", "devops", "docker", "kubernetes", "ci/cd", "aws"],
    relatedCategoryIds: ["backend", "developer-tools"],
    audience: "Developers moving from writing code to deploying and operating it.",
    publicVisibility: true,
    featured: false,
  },
  {
    id: "cybersecurity",
    slug: "cybersecurity",
    name: "Cybersecurity",
    shortDescription: "Thinking like an attacker to build safer systems.",
    introduction:
      "Cybersecurity covers the core concepts every developer should know: common vulnerability classes, the mindset of threat modeling, and where security fits into the development lifecycle.",
    icon: "cybersecurity",
    order: 9,
    searchKeywords: ["security", "infosec", "vulnerabilities", "appsec"],
    relatedCategoryIds: ["backend", "developer-tools"],
    audience: "Developers who want to build more secure systems, not penetration testers.",
    publicVisibility: true,
    featured: false,
  },
  {
    id: "testing-qa",
    slug: "testing-qa",
    name: "Software Testing and QA",
    shortDescription: "Proving software works, automatically and repeatably.",
    introduction:
      "Software testing and QA covers testing fundamentals and the tools used to automate browser, API, and regression testing so correctness doesn't depend on manual re-checking.",
    icon: "testing-qa",
    order: 10,
    searchKeywords: ["testing", "qa", "automation", "selenium", "playwright"],
    relatedCategoryIds: ["frontend", "backend", "developer-tools"],
    audience: "Developers and QA engineers who want to automate testing.",
    publicVisibility: true,
    featured: false,
  },
  {
    id: "dsa",
    slug: "dsa",
    name: "Data Structures and Algorithms",
    shortDescription: "The problem-solving toolkit behind efficient code and technical interviews.",
    introduction:
      "Data structures and algorithms covers how to represent data efficiently and reason about the time and space cost of code -- foundational for writing performant software and for technical interviews.",
    icon: "dsa",
    order: 11,
    searchKeywords: ["dsa", "algorithms", "data structures", "big o", "interview prep"],
    relatedCategoryIds: ["programming-languages"],
    audience:
      "Developers preparing for technical interviews or writing performance-sensitive code.",
    publicVisibility: true,
    featured: true,
  },
  {
    id: "developer-tools",
    slug: "developer-tools",
    name: "Developer Tools",
    shortDescription:
      "Version control, the command line, and the operating system underneath it all.",
    introduction:
      "Developer tools covers the everyday tooling every other category assumes: version control with Git, working in a terminal, and enough Linux to be comfortable on a server.",
    icon: "developer-tools",
    order: 12,
    searchKeywords: ["git", "terminal", "cli", "linux", "tooling"],
    relatedCategoryIds: ["foundations", "cloud-devops"],
    audience:
      "Anyone who wants to be comfortable with the tools professional developers use daily.",
    publicVisibility: true,
    featured: false,
  },
  {
    id: "quantitative-aptitude",
    slug: "quantitative-aptitude",
    name: "Quantitative Aptitude",
    shortDescription: "Numerical reasoning practice for placement tests.",
    introduction:
      "Quantitative aptitude practice for placement and entrance exams -- number systems, percentages, time/speed/distance, data interpretation, and more. Planned for a future phase.",
    icon: "quantitative-aptitude",
    order: 13,
    searchKeywords: ["aptitude", "quant", "placement test", "numerical reasoning"],
    relatedCategoryIds: ["reasoning"],
    audience: "Students and recent graduates preparing for placement tests.",
    // Internal draft: no topics/practice content exists yet (Phase 5). Kept
    // out of public navigation and the sitemap until it does.
    publicVisibility: false,
    featured: false,
  },
  {
    id: "reasoning",
    slug: "reasoning",
    name: "Logical and Verbal Reasoning",
    shortDescription: "Pattern recognition, verbal, and critical-reasoning practice.",
    introduction:
      "Logical and verbal reasoning practice for placement and entrance exams -- series, analogies, syllogisms, reading comprehension, and more. Planned for a future phase.",
    icon: "reasoning",
    order: 14,
    searchKeywords: ["reasoning", "logical reasoning", "verbal ability", "placement test"],
    relatedCategoryIds: ["quantitative-aptitude"],
    audience: "Students and recent graduates preparing for placement tests.",
    publicVisibility: false,
    featured: false,
  },
  {
    id: "career-gd",
    slug: "career-gd",
    name: "Career and Group Discussion Preparation",
    shortDescription: "Group discussion practice and job-readiness fundamentals.",
    introduction:
      "Career and group discussion preparation -- GD frameworks, resume basics, and interview preparation. Planned for a future phase.",
    icon: "career-gd",
    order: 15,
    searchKeywords: ["group discussion", "career prep", "interview prep", "resume"],
    relatedCategoryIds: ["quantitative-aptitude", "reasoning"],
    audience: "Students and recent graduates preparing for campus placements and interviews.",
    publicVisibility: false,
    featured: false,
  },
];
