import type { LearningPathInput } from "@/lib/directory/types";

/**
 * Every public path here is a *roadmap*: an ordered sequence of real,
 * published guides/courses/projects, explicitly not a certifiable,
 * assessed course path (Phase 8 doesn't exist yet -- see
 * `certificateEligible`/`finalAssessmentRequired`, both hard-locked to
 * false and enforced by `lib/directory/validate.ts`). "Guide-only" steps
 * are real, published content, not placeholders -- a path is only kept
 * `publicVisibility: false` when a required step would depend on a system
 * that doesn't exist yet (aptitude/reasoning/GD practice, assessments,
 * certificates), which today is exactly one path: Placement and Job
 * Readiness.
 */
export const learningPaths: LearningPathInput[] = [
  {
    id: "beginner-to-web-developer",
    slug: "complete-beginner-to-web-developer",
    name: "Complete Beginner to Web Developer",
    description:
      "Start with zero coding experience and build up to a working, deployed-quality personal website and an interactive JavaScript application.",
    intendedLearner: "Someone who has never written code before.",
    expectedOutcome:
      "Comfortable reading and writing HTML, CSS, and JavaScript, with two real projects to show for it.",
    prerequisiteIds: [],
    steps: [
      {
        id: "s1",
        type: "technology-guide",
        refId: "intro-to-programming",
        title: "Introduction to Programming",
        required: true,
      },
      {
        id: "s2",
        type: "course",
        refId: "how-computing-works",
        title: "How Computing & the Web Work",
        required: true,
      },
      {
        id: "s3",
        type: "course",
        refId: "html-css-fundamentals",
        title: "HTML & CSS Fundamentals",
        required: true,
      },
      {
        id: "s4",
        type: "project",
        refId: "personal-portfolio-page",
        title: "Personal Portfolio Page project",
        required: true,
      },
      {
        id: "s5",
        type: "course",
        refId: "javascript-fundamentals",
        title: "JavaScript Fundamentals",
        required: true,
      },
      {
        id: "s6",
        type: "project",
        refId: "interactive-quiz-app",
        title: "Interactive Quiz Application project",
        required: true,
      },
    ],
    milestones: ["Ship a working personal site", "Ship an interactive JavaScript app"],
    estimatedTimeRange: "6-10 weeks, self-paced",
    skillsEarned: ["HTML", "CSS", "JavaScript fundamentals", "The DOM", "Responsive layout"],
    requiredProjectIds: ["personal-portfolio-page", "interactive-quiz-app"],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["foundations", "frontend"],
    lastReviewed: "2026-08-01",
    relatedTechnologyIds: ["html", "css", "javascript"],
    relatedCourseIds: ["how-computing-works", "html-css-fundamentals", "javascript-fundamentals"],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "frontend-developer",
    slug: "frontend-developer",
    name: "Frontend Developer",
    description:
      "Go from HTML/CSS/JavaScript fundamentals to building interactive UIs with a modern framework.",
    intendedLearner:
      "Someone comfortable with programming basics who wants to specialize in what runs in the browser.",
    expectedOutcome:
      "Able to build responsive, accessible interfaces and understand how a component framework like React fits on top of core web fundamentals.",
    prerequisiteIds: ["intro-to-programming"],
    steps: [
      {
        id: "s1",
        type: "course",
        refId: "html-css-fundamentals",
        title: "HTML & CSS Fundamentals",
        required: true,
      },
      {
        id: "s2",
        type: "course",
        refId: "javascript-fundamentals",
        title: "JavaScript Fundamentals",
        required: true,
      },
      {
        id: "s3",
        type: "project",
        refId: "personal-portfolio-page",
        title: "Personal Portfolio Page project",
        required: true,
      },
      {
        id: "s4",
        type: "technology-guide",
        refId: "typescript",
        title: "TypeScript guide",
        required: false,
      },
      { id: "s5", type: "technology-guide", refId: "react", title: "React guide", required: true },
      { id: "s6", type: "technology-guide", refId: "sass", title: "Sass guide", required: false },
      {
        id: "s7",
        type: "project",
        refId: "interactive-quiz-app",
        title: "Interactive Quiz Application project",
        required: true,
      },
    ],
    milestones: ["Ship a responsive static site", "Understand React's component model"],
    estimatedTimeRange: "8-12 weeks, self-paced",
    skillsEarned: ["HTML", "CSS", "JavaScript", "React fundamentals"],
    requiredProjectIds: ["personal-portfolio-page", "interactive-quiz-app"],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["frontend"],
    lastReviewed: "2026-08-01",
    relatedTechnologyIds: ["html", "css", "javascript", "react", "typescript"],
    relatedCourseIds: ["html-css-fundamentals", "javascript-fundamentals"],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "backend-developer",
    slug: "backend-developer",
    name: "Backend Developer",
    description: "Learn server-side logic, REST APIs, and relational databases.",
    intendedLearner:
      "Someone comfortable with JavaScript fundamentals who wants to build server-side systems.",
    expectedOutcome: "Able to design and build a REST API backed by a relational database.",
    prerequisiteIds: ["javascript"],
    steps: [
      {
        id: "s1",
        type: "course",
        refId: "javascript-fundamentals",
        title: "JavaScript Fundamentals",
        required: true,
      },
      { id: "s2", type: "course", refId: "git-apis-sql", title: "Git, APIs & SQL", required: true },
      {
        id: "s3",
        type: "project",
        refId: "api-powered-weather-app",
        title: "API-Powered Lookup App project",
        required: true,
      },
      {
        id: "s4",
        type: "technology-guide",
        refId: "nodejs",
        title: "Node.js guide",
        required: true,
      },
      {
        id: "s5",
        type: "technology-guide",
        refId: "express",
        title: "Express guide",
        required: true,
      },
      {
        id: "s6",
        type: "technology-guide",
        refId: "postgresql",
        title: "PostgreSQL guide",
        required: false,
      },
    ],
    milestones: ["Understand REST API design", "Understand relational data modeling"],
    estimatedTimeRange: "8-12 weeks, self-paced",
    skillsEarned: ["REST API design", "SQL", "Node.js/Express fundamentals"],
    requiredProjectIds: ["api-powered-weather-app"],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["backend", "databases"],
    lastReviewed: "2026-08-01",
    relatedTechnologyIds: ["sql", "rest-apis", "nodejs", "express"],
    relatedCourseIds: ["git-apis-sql"],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "full-stack-developer",
    slug: "full-stack-developer",
    name: "Full-Stack Developer",
    description:
      "Combine frontend and backend skills into one coherent path: UI, API, and database.",
    intendedLearner:
      "Someone who wants to be able to build a complete application, frontend to database, alone.",
    expectedOutcome:
      "Able to build a full application: a UI, a REST API behind it, and a relational database storing its data.",
    prerequisiteIds: ["intro-to-programming"],
    steps: [
      {
        id: "s1",
        type: "course",
        refId: "html-css-fundamentals",
        title: "HTML & CSS Fundamentals",
        required: true,
      },
      {
        id: "s2",
        type: "course",
        refId: "javascript-fundamentals",
        title: "JavaScript Fundamentals",
        required: true,
      },
      { id: "s3", type: "course", refId: "git-apis-sql", title: "Git, APIs & SQL", required: true },
      {
        id: "s4",
        type: "project",
        refId: "api-powered-weather-app",
        title: "API-Powered Lookup App project",
        required: true,
      },
      { id: "s5", type: "technology-guide", refId: "react", title: "React guide", required: false },
      {
        id: "s6",
        type: "technology-guide",
        refId: "nodejs",
        title: "Node.js guide",
        required: true,
      },
      {
        id: "s7",
        type: "technology-guide",
        refId: "express",
        title: "Express guide",
        required: true,
      },
    ],
    milestones: ["Ship a UI", "Ship a REST API", "Connect the two to a database"],
    estimatedTimeRange: "12-16 weeks, self-paced",
    skillsEarned: ["HTML/CSS/JavaScript", "REST API design", "SQL", "Node.js/Express"],
    requiredProjectIds: ["api-powered-weather-app"],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["frontend", "backend"],
    lastReviewed: "2026-08-01",
    relatedTechnologyIds: ["html", "css", "javascript", "sql", "nodejs"],
    relatedCourseIds: ["html-css-fundamentals", "javascript-fundamentals", "git-apis-sql"],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "python-developer",
    slug: "python-developer",
    name: "Python Developer",
    description: "General-purpose Python programming, from syntax to a real project.",
    intendedLearner:
      "Someone comfortable with programming basics who wants Python as their primary language.",
    expectedOutcome:
      "Able to write well-structured, tested Python programs and understand where Python fits (scripting, backend, data).",
    prerequisiteIds: ["intro-to-programming"],
    steps: [
      {
        id: "s1",
        type: "course",
        refId: "python-fundamentals",
        title: "Python Fundamentals",
        required: true,
      },
      {
        id: "s2",
        type: "project",
        refId: "expense-tracker-cli",
        title: "Expense Tracker project",
        required: true,
      },
      {
        id: "s3",
        type: "technology-guide",
        refId: "django",
        title: "Django guide",
        required: false,
      },
      { id: "s4", type: "technology-guide", refId: "numpy", title: "NumPy guide", required: false },
    ],
    milestones: ["Ship a tested Python CLI application"],
    estimatedTimeRange: "6-10 weeks, self-paced",
    skillsEarned: [
      "Python syntax and idioms",
      "Testing fundamentals",
      "File I/O and error handling",
    ],
    requiredProjectIds: ["expense-tracker-cli"],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["programming-languages", "backend"],
    lastReviewed: "2026-08-01",
    relatedTechnologyIds: ["python", "django", "numpy"],
    relatedCourseIds: ["python-fundamentals"],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "java-developer",
    slug: "java-developer",
    name: "Java Developer",
    description:
      "A guide-based roadmap into Java and enterprise backend development with Spring Boot.",
    intendedLearner:
      "Someone comfortable with programming basics who wants to work in Java-based enterprise systems.",
    expectedOutcome:
      "Understand Java's object-oriented fundamentals and how Spring Boot builds web services on top of it.",
    prerequisiteIds: ["intro-to-programming"],
    steps: [
      {
        id: "s1",
        type: "course",
        refId: "java-programming-foundations",
        title: "Java Programming Foundations",
        required: true,
      },
      {
        id: "s2",
        type: "course",
        refId: "data-structures-and-algorithms",
        title: "Data Structures and Algorithms",
        required: false,
      },
      {
        id: "s3",
        type: "technology-guide",
        refId: "spring-boot",
        title: "Spring Boot guide",
        required: true,
      },
      {
        id: "s4",
        type: "course",
        refId: "selenium-webdriver-automation",
        title: "Selenium WebDriver Automation (optional: Java-based test automation)",
        required: false,
      },
    ],
    milestones: [
      "Understand Java's type system and OOP model",
      "Understand Spring Boot's annotation-driven structure",
    ],
    estimatedTimeRange: "8-12 weeks, self-paced",
    skillsEarned: ["Java fundamentals", "Object-oriented design", "Spring Boot basics"],
    requiredProjectIds: ["course-enrollment-progress-manager"],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["programming-languages", "backend"],
    lastReviewed: "2026-08-03",
    relatedTechnologyIds: ["java", "spring-boot", "selenium"],
    relatedCourseIds: [
      "java-programming-foundations",
      "data-structures-and-algorithms",
      "selenium-webdriver-automation",
    ],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "data-analyst",
    slug: "data-analyst",
    name: "Data Analyst",
    description:
      "Analyze and communicate insights from data using SQL, Excel, and Python's data stack.",
    intendedLearner:
      "Someone who wants to work with data professionally without a full data-science/ML focus.",
    expectedOutcome:
      "Able to query relational data, clean and summarize datasets, and communicate findings.",
    prerequisiteIds: [],
    steps: [
      { id: "s1", type: "technology-guide", refId: "excel", title: "Excel guide", required: false },
      { id: "s2", type: "course", refId: "git-apis-sql", title: "Git, APIs & SQL", required: true },
      {
        id: "s3",
        type: "technology-guide",
        refId: "pandas",
        title: "Pandas guide",
        required: true,
      },
      {
        id: "s4",
        type: "technology-guide",
        refId: "data-science-field",
        title: "Data Science guide",
        required: false,
      },
    ],
    milestones: [
      "Comfortable querying relational data with SQL",
      "Comfortable cleaning and summarizing data with Pandas",
    ],
    estimatedTimeRange: "6-10 weeks, self-paced",
    skillsEarned: ["SQL", "Pandas", "Data cleaning and summarization"],
    requiredProjectIds: [],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["data-science", "databases"],
    lastReviewed: "2026-08-01",
    relatedTechnologyIds: ["sql", "pandas", "excel"],
    relatedCourseIds: ["git-apis-sql"],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "data-scientist",
    slug: "data-scientist",
    name: "Data Scientist",
    description:
      "Python plus the numeric computing stack, for building models and analyzing complex data.",
    intendedLearner:
      "Someone comfortable with Python who wants to move into modeling and statistical analysis.",
    expectedOutcome:
      "Able to use NumPy, Pandas, and SciPy together to analyze data and understand machine learning fundamentals.",
    prerequisiteIds: ["python"],
    steps: [
      {
        id: "s1",
        type: "course",
        refId: "python-fundamentals",
        title: "Python Fundamentals",
        required: true,
      },
      { id: "s2", type: "technology-guide", refId: "numpy", title: "NumPy guide", required: true },
      {
        id: "s3",
        type: "technology-guide",
        refId: "pandas",
        title: "Pandas guide",
        required: true,
      },
      { id: "s4", type: "technology-guide", refId: "scipy", title: "SciPy guide", required: false },
      {
        id: "s5",
        type: "technology-guide",
        refId: "machine-learning",
        title: "Machine Learning guide",
        required: true,
      },
    ],
    milestones: [
      "Comfortable with the NumPy/Pandas data stack",
      "Understand machine learning fundamentals",
    ],
    estimatedTimeRange: "10-14 weeks, self-paced",
    skillsEarned: ["Python", "NumPy/Pandas/SciPy", "Machine learning fundamentals"],
    requiredProjectIds: [],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["data-science", "artificial-intelligence"],
    lastReviewed: "2026-08-01",
    relatedTechnologyIds: ["python", "numpy", "pandas", "machine-learning"],
    relatedCourseIds: ["python-fundamentals"],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "ai-genai-engineer",
    slug: "ai-and-generative-ai-engineer",
    name: "AI and Generative AI Engineer",
    description:
      "From neural network intuition to building grounded, cited retrieval-augmented AI applications.",
    intendedLearner:
      "Someone comfortable with JavaScript or Python who wants to build real AI-powered features.",
    expectedOutcome:
      "Able to explain how LLMs and RAG work, and to build a grounded, cited retrieval application.",
    prerequisiteIds: ["javascript"],
    steps: [
      {
        id: "s1",
        type: "course",
        refId: "ai-foundations",
        title: "AI, LLMs & RAG",
        required: true,
      },
      {
        id: "s2",
        type: "project",
        refId: "semantic-search-mini-app",
        title: "Semantic Search Mini-App project",
        required: true,
      },
      {
        id: "s3",
        type: "project",
        refId: "document-qa-rag-capstone",
        title: "Document Q&A RAG Capstone project",
        required: true,
      },
      {
        id: "s4",
        type: "project",
        refId: "ai-support-agent-capstone",
        title: "AI Support Agent Capstone project",
        required: false,
      },
      {
        id: "s5",
        type: "technology-guide",
        refId: "responsible-ai",
        title: "Responsible AI guide",
        required: true,
      },
    ],
    milestones: ["Understand embeddings and retrieval", "Ship a grounded, cited RAG application"],
    estimatedTimeRange: "8-12 weeks, self-paced",
    skillsEarned: [
      "LLM fundamentals",
      "Embeddings and retrieval",
      "RAG pipeline design",
      "Prompt injection defenses",
    ],
    requiredProjectIds: ["semantic-search-mini-app", "document-qa-rag-capstone"],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["artificial-intelligence"],
    lastReviewed: "2026-08-01",
    relatedTechnologyIds: ["large-language-models", "embeddings", "rag", "ai-agents"],
    relatedCourseIds: ["ai-foundations"],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "database-developer",
    slug: "database-developer",
    name: "Database Developer",
    description:
      "Relational data modeling and query design, plus an orientation to NoSQL alternatives.",
    intendedLearner: "Someone who wants to specialize in designing and querying databases.",
    expectedOutcome:
      "Able to model relational data, write efficient SQL, and know when a non-relational database fits better.",
    prerequisiteIds: [],
    steps: [
      { id: "s1", type: "course", refId: "git-apis-sql", title: "Git, APIs & SQL", required: true },
      {
        id: "s2",
        type: "course",
        refId: "database-design-and-postgresql",
        title: "Database Design and PostgreSQL",
        required: true,
      },
      { id: "s3", type: "technology-guide", refId: "mysql", title: "MySQL guide", required: false },
      {
        id: "s4",
        type: "technology-guide",
        refId: "mongodb",
        title: "MongoDB guide",
        required: true,
      },
      { id: "s5", type: "technology-guide", refId: "redis", title: "Redis guide", required: false },
    ],
    milestones: [
      "Comfortable with relational data modeling and SQL",
      "Understand when NoSQL fits better than relational",
    ],
    estimatedTimeRange: "6-10 weeks, self-paced",
    skillsEarned: ["SQL", "Relational data modeling", "Normalization", "NoSQL fundamentals"],
    requiredProjectIds: ["learning-platform-database"],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["databases"],
    lastReviewed: "2026-08-03",
    relatedTechnologyIds: ["sql", "postgresql", "mongodb"],
    relatedCourseIds: ["git-apis-sql", "database-design-and-postgresql"],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "cloud-devops-engineer",
    slug: "cloud-and-devops-engineer",
    name: "Cloud and DevOps Engineer",
    description: "Containers, orchestration, and automated deployment pipelines.",
    intendedLearner:
      "Someone comfortable with backend development who wants to move into deployment and infrastructure.",
    expectedOutcome:
      "Understand containerization, CI/CD automation, and the basics of provisioning cloud infrastructure.",
    prerequisiteIds: ["bash"],
    steps: [
      {
        id: "s1",
        type: "course",
        refId: "linux-shell-fundamentals",
        title: "Linux and Shell Fundamentals",
        required: true,
      },
      {
        id: "s2",
        type: "technology-guide",
        refId: "docker",
        title: "Docker guide",
        required: true,
      },
      { id: "s3", type: "technology-guide", refId: "ci-cd", title: "CI/CD guide", required: true },
      {
        id: "s4",
        type: "technology-guide",
        refId: "github-actions",
        title: "GitHub Actions guide",
        required: false,
      },
      {
        id: "s5",
        type: "technology-guide",
        refId: "kubernetes",
        title: "Kubernetes guide",
        required: false,
      },
      {
        id: "s6",
        type: "technology-guide",
        refId: "terraform",
        title: "Terraform guide",
        required: false,
      },
    ],
    milestones: ["Understand containerization", "Understand automated CI/CD pipelines"],
    estimatedTimeRange: "8-12 weeks, self-paced",
    skillsEarned: [
      "Docker",
      "CI/CD pipeline design",
      "Infrastructure-as-code fundamentals",
      "Shell scripting",
    ],
    requiredProjectIds: ["safe-project-validation-cli"],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["cloud-devops"],
    lastReviewed: "2026-08-03",
    relatedTechnologyIds: ["docker", "kubernetes", "ci-cd", "bash", "linux"],
    relatedCourseIds: ["linux-shell-fundamentals"],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "cybersecurity-foundations",
    slug: "cybersecurity-foundations",
    name: "Cybersecurity Foundations",
    description:
      "Understand common vulnerability classes and build the habit of reviewing code like an attacker.",
    intendedLearner:
      "Developers who want to write and review more secure code, not aspiring penetration testers.",
    expectedOutcome:
      "Able to recognize and prevent common vulnerability classes (injection, XSS, broken auth) in real code.",
    prerequisiteIds: ["sql"],
    steps: [
      { id: "s1", type: "course", refId: "git-apis-sql", title: "Git, APIs & SQL", required: true },
      {
        id: "s2",
        type: "technology-guide",
        refId: "cybersecurity-field",
        title: "Cybersecurity guide",
        required: true,
      },
      {
        id: "s3",
        type: "project",
        refId: "api-powered-weather-app",
        title: "API-Powered Lookup App project (reviewed for security)",
        required: false,
      },
    ],
    milestones: [
      "Understand common web vulnerability classes",
      "Practice threat-modeling a real feature",
    ],
    estimatedTimeRange: "4-8 weeks, self-paced",
    skillsEarned: ["Vulnerability awareness", "Secure coding habits", "Threat modeling basics"],
    requiredProjectIds: [],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["cybersecurity"],
    lastReviewed: "2026-08-01",
    relatedTechnologyIds: ["cybersecurity-field", "sql", "rest-apis"],
    relatedCourseIds: ["git-apis-sql"],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "testing-and-automation",
    slug: "software-testing-and-automation",
    name: "Software Testing and Automation",
    description: "From testing fundamentals to automated browser and API testing.",
    intendedLearner:
      "Developers or QA engineers who want to automate testing instead of relying on manual checks.",
    expectedOutcome:
      "Able to write meaningful automated tests at the unit, API, and browser levels.",
    prerequisiteIds: [],
    steps: [
      {
        id: "s1",
        type: "course",
        refId: "python-fundamentals",
        title: "Python Fundamentals (includes a testing lesson)",
        required: true,
      },
      {
        id: "s2",
        type: "technology-guide",
        refId: "api-testing",
        title: "API Testing guide",
        required: true,
      },
      {
        id: "s3",
        type: "technology-guide",
        refId: "postman",
        title: "Postman guide",
        required: false,
      },
      {
        id: "s4",
        type: "course",
        refId: "playwright-web-automation",
        title: "Playwright Web Automation",
        required: true,
      },
      {
        id: "s5",
        type: "course",
        refId: "selenium-webdriver-automation",
        title: "Selenium WebDriver Automation (optional: Java-based alternative)",
        required: false,
      },
      {
        id: "s6",
        type: "course",
        refId: "test-automation-framework-engineering",
        title: "Test Automation Framework Engineering",
        required: false,
      },
    ],
    milestones: ["Write meaningful unit tests", "Automate a browser-based test"],
    estimatedTimeRange: "6-10 weeks, self-paced",
    skillsEarned: [
      "Testing fundamentals",
      "API testing",
      "Browser test automation",
      "Automation framework design",
    ],
    requiredProjectIds: ["cross-browser-learning-platform-test-suite"],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["testing-qa"],
    lastReviewed: "2026-08-03",
    relatedTechnologyIds: ["testing-fundamentals", "playwright-testing", "api-testing", "selenium"],
    relatedCourseIds: [
      "python-fundamentals",
      "playwright-web-automation",
      "selenium-webdriver-automation",
      "test-automation-framework-engineering",
    ],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "mobile-app-developer",
    slug: "mobile-app-developer",
    name: "Mobile App Developer",
    description: "An orientation to native and cross-platform mobile development options.",
    intendedLearner: "Someone comfortable with programming basics who wants to build mobile apps.",
    expectedOutcome:
      "Understand the trade-offs between React Native, Flutter, and native (Kotlin/Swift) development.",
    prerequisiteIds: ["javascript"],
    steps: [
      {
        id: "s1",
        type: "technology-guide",
        refId: "react",
        title: "React guide (prerequisite for React Native)",
        required: false,
      },
      {
        id: "s2",
        type: "technology-guide",
        refId: "react-native",
        title: "React Native guide",
        required: true,
      },
      {
        id: "s3",
        type: "technology-guide",
        refId: "flutter",
        title: "Flutter guide",
        required: false,
      },
      {
        id: "s4",
        type: "technology-guide",
        refId: "kotlin",
        title: "Kotlin guide",
        required: false,
      },
      { id: "s5", type: "technology-guide", refId: "swift", title: "Swift guide", required: false },
    ],
    milestones: ["Understand cross-platform vs. native trade-offs"],
    estimatedTimeRange: "8-12 weeks, self-paced",
    skillsEarned: ["Mobile development fundamentals", "Cross-platform framework orientation"],
    requiredProjectIds: [],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["mobile"],
    lastReviewed: "2026-08-01",
    relatedTechnologyIds: ["react-native", "flutter", "kotlin", "swift"],
    relatedCourseIds: [],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "zero-to-ai-builder",
    slug: "zero-to-ai-builder",
    name: "Zero to AI Builder",
    description:
      "Start with zero coding experience and build up to a real, cited retrieval-augmented AI application.",
    intendedLearner:
      "A complete beginner whose end goal is specifically to build AI-powered applications.",
    expectedOutcome:
      "Comfortable with programming fundamentals and able to build a grounded, cited RAG application from scratch.",
    prerequisiteIds: [],
    steps: [
      {
        id: "s1",
        type: "course",
        refId: "how-computing-works",
        title: "How Computing & the Web Work",
        required: true,
      },
      {
        id: "s2",
        type: "course",
        refId: "python-fundamentals",
        title: "Python Fundamentals",
        required: true,
      },
      {
        id: "s3",
        type: "course",
        refId: "ai-foundations",
        title: "AI, LLMs & RAG",
        required: true,
      },
      {
        id: "s4",
        type: "project",
        refId: "semantic-search-mini-app",
        title: "Semantic Search Mini-App project",
        required: true,
      },
      {
        id: "s5",
        type: "project",
        refId: "document-qa-rag-capstone",
        title: "Document Q&A RAG Capstone project",
        required: true,
      },
    ],
    milestones: ["Complete programming fundamentals", "Ship a grounded, cited RAG application"],
    estimatedTimeRange: "12-16 weeks, self-paced",
    skillsEarned: ["Programming fundamentals", "Python", "LLM and RAG fundamentals"],
    requiredProjectIds: ["semantic-search-mini-app", "document-qa-rag-capstone"],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["foundations", "artificial-intelligence"],
    lastReviewed: "2026-08-01",
    relatedTechnologyIds: ["intro-to-programming", "python", "rag"],
    relatedCourseIds: ["how-computing-works", "python-fundamentals", "ai-foundations"],
    publicVisibility: true,
    roadmapOnly: true,
  },
  {
    id: "placement-job-readiness",
    slug: "placement-and-job-readiness",
    name: "Placement and Job Readiness",
    description:
      "Quantitative aptitude, reasoning, group discussion, and interview preparation for campus placements.",
    intendedLearner: "Students and recent graduates preparing for placement tests and interviews.",
    expectedOutcome:
      "Confident performance in aptitude tests, reasoning tests, group discussions, and technical interviews.",
    prerequisiteIds: [],
    steps: [
      {
        id: "s1",
        type: "practice",
        refId: "quantitative-aptitude",
        title: "Quantitative aptitude practice",
        required: true,
      },
      {
        id: "s2",
        type: "practice",
        refId: "reasoning",
        title: "Logical and verbal reasoning practice",
        required: true,
      },
      {
        id: "s3",
        type: "practice",
        refId: "career-gd",
        title: "Group discussion and interview preparation",
        required: true,
      },
    ],
    milestones: [],
    estimatedTimeRange: "Not yet available",
    skillsEarned: [
      "Quantitative aptitude",
      "Logical and verbal reasoning",
      "Group discussion technique",
      "Interview preparation",
    ],
    requiredProjectIds: [],
    finalAssessmentRequired: false,
    certificateEligible: false,
    primaryCategoryIds: ["quantitative-aptitude", "reasoning", "career-gd"],
    lastReviewed: "2026-08-01",
    relatedTechnologyIds: [],
    relatedCourseIds: [],
    // Internal draft: every required step depends on Aptitude/Reasoning/GD
    // content that does not exist yet (Phase 5). Not public until it does.
    publicVisibility: false,
    roadmapOnly: true,
  },
];
